
CREATE DATABASE BASE_ALUMNOS
GO

USE BASE_ALUMNOS
GO

CREATE TABLE ALUMNO
(
	ID_ALUMNO INT PRIMARY KEY IDENTITY,
	RUT NVARCHAR(15) NOT NULL,
	PRIMER_NOMBRE NVARCHAR(20) NOT NULL,
	SEGUNDO_NOMBRE NVARCHAR(20),
	PRIMER_APELLIDO NVARCHAR(20) NOT NULL,
	SEGUNDO_APELLIDO NVARCHAR(20),
	FECHA_NACIMIEMTO DATE NOT NULL,
	FECHA_INGRESO DATE NOT NULL
)
GO
