//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public int ID_ALUMNO { get; set; }
        public string RUT { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public System.DateTime FECHA_INGOROESO { get; set; }
    }
}
